//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Hauptverantwortliche
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Hauptverant
    {
        public Nullable<System.DateTime> STICHTAG { get; set; }
        public string MANDANT { get; set; }
        public string OBJEKTGES { get; set; }
        public string LIEGNR { get; set; }
        public string LIEGBEZ { get; set; }
        public Nullable<double> Objektschluessel_Liegenschaft { get; set; }
        public string Buchungskreis { get; set; }
        public string Hauptverantwortlich { get; set; }
        public string User_Kategorie { get; set; }
        public string User_Name_Vorname { get; set; }
        public string Zweit_Prüfer_Berechtigt { get; set; }
        public string keys { get; set; }
        public int ID { get; set; }
    }
}
